CREATE TABLE accounts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    submittedAt DATE,
    dsp VARCHAR(100),
    mobileNumber VARCHAR(20),
    simStatus VARCHAR(50),
    idType VARCHAR(100),
    firstName VARCHAR(100),
    lastName VARCHAR(100),
    middleName VARCHAR(100),
    storeName VARCHAR(200),
    fullAddress TEXT,
    latitude VARCHAR(50),
    longitude VARCHAR(50),
    mpin VARCHAR(10),
    accountStatus VARCHAR(20) DEFAULT 'Pending',
    progressStatus VARCHAR(100),
    onSystem BOOLEAN DEFAULT FALSE,
    hasDti BOOLEAN DEFAULT FALSE,
    hasSelfie BOOLEAN DEFAULT FALSE,
    hasStorePhoto BOOLEAN DEFAULT FALSE,
    hasSyncedGpo BOOLEAN DEFAULT FALSE,
    remark TEXT,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
